// Copyright (c) 2013 Titanium I.T. LLC. All rights reserved. See LICENSE.TXT for details.
(function() {
	"use strict";

	describe("UI", function() {
		var samples;
		var userCode;
		var showBuiltins;
		var showAllFunctions;
		var evaluate;
		var graph;

		beforeEach(function() {
			document.body.innerHTML +=
				"<ul id='samples'></ul>" +
				"<textarea id='userCode'></textarea>" +
				"<input id='evaluate' type='submit'>" +
				"<input id='builtins' type='checkbox'>" +
				"<input id='functions' type='checkbox'>" +
				"<div id='graph'></div>";

			samples = document.getElementById("samples");
			userCode = document.getElementById("userCode");
			evaluate = document.getElementById("evaluate");
			showBuiltins = document.getElementById("builtins");
			showAllFunctions = document.getElementById("functions");
			graph = document.getElementById("graph");

			jdls.ui.initialize({
				samplesList: samples,
				userCodeTextArea: userCode,
				evaluateButton: evaluate,
				showBuiltinsCheckbox: showBuiltins,
				graphDiv: graph
			});
		});

		afterEach(function() {
			document.body.removeChild(samples);
			document.body.removeChild(userCode);
			document.body.removeChild(evaluate);
			document.body.removeChild(graph);
		});

		describe("initialization", function() {
			var defaultSample;

			beforeEach(function() {
				defaultSample = jdls.usercode.DEFAULT_SAMPLE;
			});

			it("populates sample buttons", function() {
				expect(samples.innerHTML).to.contain(defaultSample.name);
				//TODO: escape button names
			});

			// TODO: test sample buttons' event handler

			it("puts default user code into text area", function() {
				expect(userCode.value).to.equal(defaultSample.code);
			});

			it("draws graph", function() {
				expect(graph.innerHTML).to.contain("Generated by graphviz");
			});
		});

		describe("options", function() {
			it("respects 'show builtins' checkbox", function() {
				userCode.value = "this.a = [];";
				showBuiltins.checked = true;
				evaluate.click();
				expect(graph.innerHTML).to.contain("Array {Object}");
			});
		});

		describe("interactivity", function() {
			it("re-draws graph when button clicked", function() {
				userCode.value = "this.a = 1;";
				evaluate.click();
				expect(graph.innerHTML).to.contain("a: 1");
			});

			it("displays exception when bad code entered", function() {
				userCode.value = "asdf";
				evaluate.click();
				expect(graph.innerHTML).to.contain("<pre>ReferenceError");
			});
		});

	});

}());